services:
  hexerade:
    restart: unless-stopped
    build: .
    env_file: '.env'
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./sql:/app/sql
      - ./certs:/app/certs
